#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled 3"
  https://create.arduino.cc/cloud/things/ace7bed8-e6d0-4f96-89c0-a1708bd0e09f 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float kWh;
  float sensorValueA0;
  float voltageA0;
  float voltageA1;
  CloudLight h1;
  CloudLight h2;
  CloudLight reset;
  CloudLight set;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/
float teste = 0;
float volteste = 0;
float estadoentrada1 = 0;
#define entrada A1

#include "thingProperties.h"

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);
  
  pinMode(D0,OUTPUT);
  pinMode(D1,OUTPUT);
  pinMode(D2,OUTPUT);
  pinMode(D3,OUTPUT);
  pinMode(entrada, INPUT);
  pinMode(LED_D0,OUTPUT);
  pinMode(LED_D1,OUTPUT);
  pinMode(LED_D2,OUTPUT);
  pinMode(LED_D3,OUTPUT);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  
  estadoentrada1 = digitalRead(entrada);
  if (estadoentrada1 == HIGH) {
    kWh = kWh + 0.00001;
  }

  if (set == 1) {
    digitalWrite(D0,HIGH);
    digitalWrite(LED_D0,HIGH);
  }else{
    digitalWrite(D0,LOW);
    digitalWrite(LED_D0,LOW);
  }
  
  if (reset == 1) {
    digitalWrite(D1,HIGH);
    digitalWrite(LED_D1,HIGH);
  }else{
    digitalWrite(D1,LOW);
    digitalWrite(LED_D1,LOW);
  }
  
  sensorValueA0 = analogRead(A0);
  voltageA0 = sensorValueA0 * (3.0 / 4095.0) / 0.3 + 0.827;
  volteste = voltageA0 * 20;
  voltageA1 = volteste;
  
  if (voltageA1 <= 30) {
    digitalWrite(D2,HIGH);  
    digitalWrite(LED_D2,HIGH);
    digitalWrite(D3,LOW);
    digitalWrite(LED_D3,LOW);
    h1 = HIGH;
    h2 = LOW;
  }
  
  if (voltageA1 >= 40) {
    digitalWrite(D2,LOW);
    digitalWrite(LED_D2,LOW);
    digitalWrite(D3,HIGH);
    digitalWrite(LED_D3,HIGH);
    h1 = LOW;
    h2 = HIGH;
  }
}


/*
  Since Set is READ_WRITE variable, onSetChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onSetChange()  {
  // Add your code here to act upon Set change
}

/*
  Since Reset is READ_WRITE variable, onResetChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onResetChange()  {
  // Add your code here to act upon Reset change
}









